CREATE SCHEMA MONEYMANAGEMENT;

CREATE TABLE MONEYMANAGEMENT.TRANSAXION_SUBTYPE (
  ID CHAR(1) NOT NULL,
  DESCRIPTION VARCHAR(10) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE MONEYMANAGEMENT.TRANSAXION_TYPE (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  SUBTYPE_ID CHAR(1) NOT NULL,
  DESCRIPTION VARCHAR(25) NOT NULL,
  PRIMARY KEY(ID),
  UNIQUE(SUBTYPE_ID,DESCRIPTION)
);
ALTER TABLE MONEYMANAGEMENT.TRANSAXION_TYPE ADD FOREIGN KEY(SUBTYPE_ID) REFERENCES MONEYMANAGEMENT.TRANSAXION_SUBTYPE(ID);

CREATE TABLE MONEYMANAGEMENT.TRANSAXION (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  TYPE_ID INTEGER NOT NULL,
  DATE DATE NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL,
  VALUE DOUBLE NOT NULL,
  PRIMARY KEY(ID)
);
ALTER TABLE MONEYMANAGEMENT.TRANSAXION ADD FOREIGN KEY(TYPE_ID) REFERENCES MONEYMANAGEMENT.TRANSAXION_TYPE(ID);

CREATE TABLE MONEYMANAGEMENT.OUTCOME (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  TRANSACTION_ID INTEGER NOT NULL,
  MANDATORY SMALLINT,
  EXTRA SMALLINT,
  PRIMARY KEY(ID)
);
ALTER TABLE MONEYMANAGEMENT.OUTCOME ADD FOREIGN KEY(TRANSACTION_ID) REFERENCES MONEYMANAGEMENT.TRANSAXION(ID);

CREATE TABLE MONEYMANAGEMENT.INCOME (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  TRANSACTION_ID INTEGER NOT NULL,
  PRIMARY KEY(ID)
);
ALTER TABLE MONEYMANAGEMENT.INCOME ADD FOREIGN KEY(TRANSACTION_ID) REFERENCES MONEYMANAGEMENT.TRANSAXION(ID);

INSERT INTO MONEYMANAGEMENT.TRANSAXION_SUBTYPE values ('O', 'USCITA');
INSERT INTO MONEYMANAGEMENT.TRANSAXION_SUBTYPE values ('I', 'ENTRATA');
INSERT INTO MONEYMANAGEMENT.TRANSAXION_TYPE(SUBTYPE_ID,DESCRIPTION) VALUES ('O', 'PRELIEVO');
INSERT INTO MONEYMANAGEMENT.TRANSAXION_TYPE(SUBTYPE_ID,DESCRIPTION) VALUES ('O', 'CARTA');
INSERT INTO MONEYMANAGEMENT.TRANSAXION_TYPE(SUBTYPE_ID,DESCRIPTION) VALUES ('O', 'CONTANTI');
INSERT INTO MONEYMANAGEMENT.TRANSAXION_TYPE(SUBTYPE_ID,DESCRIPTION) VALUES ('O', 'BONIFICO IN USCITA');
INSERT INTO MONEYMANAGEMENT.TRANSAXION_TYPE(SUBTYPE_ID,DESCRIPTION) VALUES ('O', 'RID');
INSERT INTO MONEYMANAGEMENT.TRANSAXION_TYPE(SUBTYPE_ID,DESCRIPTION) VALUES ('O', 'CONTO ONLINE');
INSERT INTO MONEYMANAGEMENT.TRANSAXION_TYPE(SUBTYPE_ID,DESCRIPTION) VALUES ('I', 'BONIFICO IN ENTRATA');
INSERT INTO MONEYMANAGEMENT.TRANSAXION_TYPE(SUBTYPE_ID,DESCRIPTION) VALUES ('I', 'CONTANTI');

END_DB_CONFIG;