package it.moneymanagement.business.dao.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Income generated by hbm2java
 */
@Entity
@Table(name = "income", catalog = "moneymanagement")
public class IncomeEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private TransaxionEntity transaxion;

	public IncomeEntity() {
	}

	public IncomeEntity(TransaxionEntity transaxion) {
		this.transaxion = transaxion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TRANSACTION_ID", nullable = false)
	public TransaxionEntity getTransaxion() {
		return this.transaxion;
	}

	public void setTransaxion(TransaxionEntity transaxion) {
		this.transaxion = transaxion;
	}

}
