package it.moneymanagement.business.dao.entity;
// Generated 4-apr-2011 18.25.21 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Outcome generated by hbm2java
 */
@Entity
@Table(name = "outcome", catalog = "moneymanagement")
public class OutcomeEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private TransaxionEntity transaxion;
	private Short mandatory;
	private Short extra;

	public OutcomeEntity() {
	}

	public OutcomeEntity(TransaxionEntity transaxion) {
		this.transaxion = transaxion;
	}
	public OutcomeEntity(TransaxionEntity transaxion, Short mandatory, Short extra) {
		this.transaxion = transaxion;
		this.mandatory = mandatory;
		this.extra = extra;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TRANSACTION_ID", nullable = false)
	public TransaxionEntity getTransaxion() {
		return this.transaxion;
	}

	public void setTransaxion(TransaxionEntity transaxion) {
		this.transaxion = transaxion;
	}

	@Column(name = "MANDATORY")
	public Short getMandatory() {
		return this.mandatory;
	}

	public void setMandatory(Short mandatory) {
		this.mandatory = mandatory;
	}

	@Column(name = "EXTRA")
	public Short getExtra() {
		return this.extra;
	}

	public void setExtra(Short extra) {
		this.extra = extra;
	}

}
