package it.moneymanagement.business.dao.entity;
// Generated 4-apr-2011 18.25.21 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaxion generated by hbm2java
 */
@Entity
@Table(name = "transaxion", catalog = "moneymanagement")
public class TransaxionEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private TransaxionTypeEntity transaxionType;
	private Date date;
	private String description;
	private double value;

	public TransaxionEntity() {
	}

	public TransaxionEntity(TransaxionTypeEntity transaxionType, Date date,
			String description, double value) {
		this.transaxionType = transaxionType;
		this.date = date;
		this.description = description;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TYPE_ID", nullable = false)
	public TransaxionTypeEntity getTransaxionType() {
		return this.transaxionType;
	}

	public void setTransaxionType(TransaxionTypeEntity transaxionType) {
		this.transaxionType = transaxionType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "VALUE", nullable = false, precision = 22, scale = 0)
	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

}
