package it.moneymanagement.business.dao.entity;
// Generated 4-apr-2011 18.25.21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TransaxionSubtype generated by hbm2java
 */
@Entity
@Table(name = "transaxion_subtype", catalog = "moneymanagement")
public class TransaxionSubtypeEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private char id;
	private String description;

	public TransaxionSubtypeEntity() {
	}

	public TransaxionSubtypeEntity(char id, String description) {
		this.id = id;
		this.description = description;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 1)
	public char getId() {
		return this.id;
	}

	public void setId(char id) {
		this.id = id;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 10)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
