package it.moneymanagement.business.dao.entity;
// Generated 4-apr-2011 18.25.21 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TransaxionType generated by hbm2java
 */
@Entity
@Table(name = "transaxion_type", catalog = "moneymanagement", uniqueConstraints = @UniqueConstraint(columnNames = {
		"SUBTYPE_ID", "DESCRIPTION"}))
public class TransaxionTypeEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private TransaxionSubtypeEntity transaxionSubtype;
	private String description;

	public TransaxionTypeEntity() {
	}

	public TransaxionTypeEntity(TransaxionSubtypeEntity transaxionSubtype,
			String description) {
		this.transaxionSubtype = transaxionSubtype;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SUBTYPE_ID", nullable = false)
	public TransaxionSubtypeEntity getTransaxionSubtype() {
		return this.transaxionSubtype;
	}

	public void setTransaxionSubtype(TransaxionSubtypeEntity transaxionSubtype) {
		this.transaxionSubtype = transaxionSubtype;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 25)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
